import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="fixed top-4 left-4 z-50">
          <a href="https://wathematica.github.io/" >
            <img src="/wathematica_logo.png" alt="ロゴ" className="h-12 w-12 rounded-full shadow-md" />
          </a>
        </header>
        {children}
        <footer className="fixed bottom-2 left-1/2 z-50 transform -translate-x-1/2">
          @Created by とりさん
        </footer>
      </body>
    </html>
  );
}
